'use client';

import ImageCarousel from '@/components/ImageCarousel';
import JournalEntryDetail from '@/components/JournalEntryDetail';
import { JournalEntry } from '@/lib/airtable';
import { useEffect, useState } from 'react';

// Mock data until Airtable integration is complete
const MOCK_ENTRIES: JournalEntry[] = [
  {
    id: '1',
    title: 'First memories',
    date: '2023-01-15',
    content: 'These are the traces of memories lost to light. Moments captured in time that tell a story of a journey.\n\nSome details fade, but the images help bring back the feelings of those days.',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba',
  },
  {
    id: '2',
    title: 'Summer reflections',
    date: '2023-06-22',
    content: 'The summer light created the perfect moment. I found myself reflecting on how time passes and what remains.\n\nThese images are more than just pictures - they are doorways to moments I never want to forget.',
    image: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8',
  },
  {
    id: '3',
    title: 'Winter passage',
    date: '2023-12-10',
    content: 'The stillness of winter has its own voice. In the quiet moments, memories feel more vivid, more present.\n\nI captured this image to remember the feeling of solitude that wasn\'t lonely, but peaceful.',
    image: 'https://images.unsplash.com/photo-1483664852095-d6cc6870702d',
  },
];

export default function Home() {
  const [entries, setEntries] = useState<JournalEntry[]>(MOCK_ENTRIES);
  const [selectedEntry, setSelectedEntry] = useState<JournalEntry | null>(entries[0] || null);
  const [loading, setLoading] = useState(true);

  // This would be used to fetch real data from Airtable
  // Commented out until we have proper environment variables set up
  /*
  useEffect(() => {
    async function fetchEntries() {
      try {
        const fetchedEntries = await getJournalEntries();
        if (fetchedEntries.length > 0) {
          setEntries(fetchedEntries);
          setSelectedEntry(fetchedEntries[0]);
        }
        setLoading(false);
      } catch (error) {
        console.error('Failed to fetch journal entries:', error);
        setLoading(false);
      }
    }

    fetchEntries();
  }, []);
  */

  // Using mock data for now
  useEffect(() => {
    // Simulate loading
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1000);
    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="flex flex-col h-screen overflow-hidden bg-black text-white">
      {/* Header */}
      <header className="pt-6 px-6 md:px-10">
        <div className="max-w-5xl mx-auto">
          <h1 className="text-4xl sm:text-5xl font-bold tracking-tight text-center mb-2">MEMOIR</h1>
          <div className="text-center text-gray-400 text-sm uppercase tracking-widest">
            <p>AN ARCHIVE OF SRIRAM'S</p>
            <p>TRACES LOST TO LIGHT</p>
          </div>
        </div>
      </header>

      <main className="flex-1 flex flex-col justify-center items-center px-6 md:px-10 relative">
        {loading ? (
          <div className="flex items-center justify-center w-full h-full">
            <div className="animate-pulse bg-gray-800 w-full max-w-[600px] aspect-square"></div>
          </div>
        ) : (
          <div className="w-full max-w-5xl mx-auto flex flex-col items-center space-y-4">
            {/* Image Carousel - centerpiece of the page */}
            <ImageCarousel 
              entries={entries} 
              onEntrySelected={setSelectedEntry} 
            />

            {/* Journal Entry Details */}
            <JournalEntryDetail entry={selectedEntry} />
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="pb-3 px-6 text-center text-xs text-gray-500">
        <p>*IMAGES ARE GENERATED BY AI</p>
      </footer>
    </div>
  );
}
