'use client';

import ImageCarousel from '@/components/ImageCarousel';
import JournalEntryDetail from '@/components/JournalEntryDetail';
import { JournalEntryWithImage } from '@/lib/airtable';
import { useEffect, useState } from 'react';

// Mock data until Airtable integration is complete
const MOCK_ENTRIES: JournalEntryWithImage[] = [
  {
    id: '1',
    title: 'First memories',
    date: '2023-01-15',
    content: 'These are the traces of memories lost to light. Moments captured in time that tell a story of a journey.\n\nSome details fade, but the images help bring back the feelings of those days.',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba',
  },
  {
    id: '2',
    title: 'Summer reflections',
    date: '2023-06-22',
    content: 'The summer light created the perfect moment. I found myself reflecting on how time passes and what remains.\n\nThese images are more than just pictures - they are doorways to moments I never want to forget.',
    image: 'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8',
  },
  {
    id: '3',
    title: 'Winter passage',
    date: '2023-12-10',
    content: 'The stillness of winter has its own voice. In the quiet moments, memories feel more vivid, more present.\n\nI captured this image to remember the feeling of solitude that wasn\'t lonely, but peaceful.',
    image: 'https://images.unsplash.com/photo-1483664852095-d6cc6870702d',
  },
];

// Mock page content
const MOCK_PAGE_CONTENT = {
  title: 'MEMOIR',
  subtitle1: 'AN ARCHIVE OF SRIRAM&apos;S',
  subtitle2: 'TRACES LOST TO LIGHT',
  footer: '*IMAGES ARE GENERATED BY AI'
};

export default function Home() {
  const [entries] = useState<JournalEntryWithImage[]>(MOCK_ENTRIES);
  const [selectedEntry, setSelectedEntry] = useState<JournalEntryWithImage | null>(entries[0] || null);
  const [loading, setLoading] = useState(true);
  const [pageContent] = useState(MOCK_PAGE_CONTENT);

  // This would be used to fetch real data from Airtable
  // Commented out until we have proper environment variables set up
  /*
  useEffect(() => {
    async function fetchData() {
      try {
        // Fetch journal entries with images
        const fetchedEntries = await getJournalEntriesWithImages();
        if (fetchedEntries.length > 0) {
          setEntries(fetchedEntries);
          setSelectedEntry(fetchedEntries[0]);
        }
        
        // Fetch page content
        const content = await getPageContent();
        setPageContent({
          title: content.title || MOCK_PAGE_CONTENT.title,
          subtitle1: content.subtitle1 || MOCK_PAGE_CONTENT.subtitle1,
          subtitle2: content.subtitle2 || MOCK_PAGE_CONTENT.subtitle2,
          footer: content.footer || MOCK_PAGE_CONTENT.footer
        });
        
        setLoading(false);
      } catch (error) {
        console.error('Failed to fetch data:', error);
        setLoading(false);
      }
    }

    fetchData();
  }, []);
  */

  // Using mock data for now
  useEffect(() => {
    // Simulate loading
    const timer = setTimeout(() => {
      setLoading(false);
    }, 1000);
    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="flex flex-col h-screen overflow-hidden bg-black text-white">
      {/* Header */}
      <header className="pt-6 px-6 md:px-10">
        <div className="max-w-5xl mx-auto">
          <h1 className="text-4xl sm:text-5xl font-medium tracking-tight text-center mb-2 font-futura-medium">
            {pageContent.title}
          </h1>
          <div className="text-center text-gray-400 text-sm uppercase tracking-widest font-futura-light">
            <p>{pageContent.subtitle1}</p>
            <p>{pageContent.subtitle2}</p>
          </div>
        </div>
      </header>

      <main className="flex-1 flex flex-col justify-center items-center px-6 md:px-10 relative">
        {loading ? (
          <div className="flex items-center justify-center w-full h-full">
            <div className="animate-pulse bg-gray-800 w-full max-w-[600px] aspect-square"></div>
          </div>
        ) : (
          <div className="w-full max-w-5xl mx-auto flex flex-col items-center space-y-4">
            {/* Image Carousel - centerpiece of the page */}
            <ImageCarousel 
              entries={entries} 
              onEntrySelected={setSelectedEntry} 
            />

            {/* Journal Entry Details */}
            <JournalEntryDetail entry={selectedEntry} />
          </div>
        )}
      </main>

      {/* Footer */}
      <footer className="pb-3 px-6 text-center text-xs text-gray-500 font-futura-light">
        <p>{pageContent.footer}</p>
      </footer>
    </div>
  );
}
